version: '3.8'

services:
  nginx:
    image: library/nginx:1.22.1-alpine
    container_name: templatedocker_nginx
    ports:
      - "30080:80"
      - "30043:443"
    build: ./php
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html
  php:
    image: sexvideophp
    build: ./php
    restart: always
    container_name: templatedocker_php
    ports:
      - 9000:9000
    volumes:
      - ./www:/var/www/html
  mysql:
    image: mysql:8.0
    container_name: templatedocker_mysql8
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone='+8:00' --ssl=0 --sql-mode="" --default-authentication-plugin=mysql_native_password
    ports:
      - "30036:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_USERNAME: sexvideo
      MYSQL_PASSWORD: 1234qwer
      MYSQL_ROOT_PASSWORD: 1234qwer
      MYSQL_DATABASE: sexvideo
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: templatedocker_phpmyadmin
    restart: always
    ports:
      - "30081:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
  redis:
    image: redis
    container_name: templatedocker_redis
    restart: always
    ports:
      - "30079:6379"